# Generated by Django 4.1.11 on 2023-09-16 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('slug', models.SlugField(max_length=200)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('date', models.DateField(auto_now_add=True)),
                ('sub_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('image', models.ImageField(null=True, upload_to='')),
                ('detal', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('number', models.IntegerField(default=0, null=True)),
                ('Category', models.ManyToManyField(related_name='productss', to='home.category')),
            ],
        ),
    ]
